//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace MiniaturePrice1.PricingService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PricingServiceSoap", Namespace="http://tempuri.org/")]
    public partial class PricingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CalculateFutureContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateFutureContractListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PricingService() {
            this.Url = global::MiniaturePrice1.Properties.Settings.Default.MiniaturePrice1_PricingService_PricingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CalculateFutureContractCompletedEventHandler CalculateFutureContractCompleted;
        
        /// <remarks/>
        public event CalculateFutureContractListCompletedEventHandler CalculateFutureContractListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateFutureContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal CalculateFutureContract(decimal currentPrice, short dayInYear) {
            object[] results = this.Invoke("CalculateFutureContract", new object[] {
                        currentPrice,
                        dayInYear});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateFutureContractAsync(decimal currentPrice, short dayInYear) {
            this.CalculateFutureContractAsync(currentPrice, dayInYear, null);
        }
        
        /// <remarks/>
        public void CalculateFutureContractAsync(decimal currentPrice, short dayInYear, object userState) {
            if ((this.CalculateFutureContractOperationCompleted == null)) {
                this.CalculateFutureContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateFutureContractOperationCompleted);
            }
            this.InvokeAsync("CalculateFutureContract", new object[] {
                        currentPrice,
                        dayInYear}, this.CalculateFutureContractOperationCompleted, userState);
        }
        
        private void OnCalculateFutureContractOperationCompleted(object arg) {
            if ((this.CalculateFutureContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateFutureContractCompleted(this, new CalculateFutureContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateFutureContractList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal[] CalculateFutureContractList(decimal[] currentPriceList, short dayInYear) {
            object[] results = this.Invoke("CalculateFutureContractList", new object[] {
                        currentPriceList,
                        dayInYear});
            return ((decimal[])(results[0]));
        }
        
        /// <remarks/>
        public void CalculateFutureContractListAsync(decimal[] currentPriceList, short dayInYear) {
            this.CalculateFutureContractListAsync(currentPriceList, dayInYear, null);
        }
        
        /// <remarks/>
        public void CalculateFutureContractListAsync(decimal[] currentPriceList, short dayInYear, object userState) {
            if ((this.CalculateFutureContractListOperationCompleted == null)) {
                this.CalculateFutureContractListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateFutureContractListOperationCompleted);
            }
            this.InvokeAsync("CalculateFutureContractList", new object[] {
                        currentPriceList,
                        dayInYear}, this.CalculateFutureContractListOperationCompleted, userState);
        }
        
        private void OnCalculateFutureContractListOperationCompleted(object arg) {
            if ((this.CalculateFutureContractListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateFutureContractListCompleted(this, new CalculateFutureContractListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CalculateFutureContractCompletedEventHandler(object sender, CalculateFutureContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateFutureContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateFutureContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CalculateFutureContractListCompletedEventHandler(object sender, CalculateFutureContractListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateFutureContractListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateFutureContractListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591